apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-app-configmap
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: crud-app
data: 
  application.yml: |-
    spring:
      datasource:
        url: "jdbc:postgresql://{{ template "postgresql.hostname" . }}:{{- .Values.postgresql.primary.service.ports.postgresql -}}/{{- .Values.postgresql.auth.database -}}"
        username: {{ .Values.configuration.spring.datasource.username }}
        password: {{ .Values.configuration.spring.datasource.password }}
        platform: {{ .Values.configuration.spring.datasource.platform }}
      jpa:
        show-sql: {{ .Values.configuration.spring.jpa.showsql }}
        generate-ddl: {{ .Values.configuration.spring.jpa.generateddl }}
        hibernate.ddl-auto: {{ .Values.configuration.spring.jpa.hibernateddlauto }}
        database-platform: {{ .Values.configuration.spring.jpa.databaseplatform }}