apiVersion: v1
kind: Service
metadata:
  name: crud-service
  labels:
    app: crud-service
spec:
  selector:
    app: crud-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.appPort }}
      targetPort: 8000