nginx-ingress:
    controller:
        enableSnippets: true

fullNameOverride: crud-app

deployment:
    replicas: 1
    appImage: nickolaytalalayeu/crud-app-hw7
    appVersion: apps/v1
    
service:
    appPort: 80

ingress:
    hostname: arch.homework
    appPort: 80
    path: /

configuration:
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgresCrudDB
      username: postgresCrud
      password: postgresCrud
      platform: postgresql
    jpa:
      showsql: true
      generateddl: false
      hibernateddlauto: validate
      databaseplatform: org.hibernate.dialect.PostgreSQLDialect

postgresql:
  postgresqlUsername: postgresCrud
  postgresqlPassword: postgresCrud
  postgresqlDatabase: postgresCrudDB
  initdbScripts:
    db-init.sql: |
      create sequence hibernate_sequence start with 1 increment by 1;
      create table users (id bigint not null, username varchar(255), firstname varchar(255), lastname varchar(255), email varchar(255), phone varchar(255), primary key (id));
      insert into users(id,username,firstname,lastname,email,phone) values(1,'FirstUser', 'Bob', 'Milan', 'milan.bob@gmail.com', '84922204006');
      insert into users(id,username,firstname,lastname,email,phone) values(2,'BigBoy', 'Alan', 'ronin', 'bigboy229@gmail.com', '83862214476');
