apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-crud-service
  labels:
    app: crud-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: crud-service
            port:
              number: {{ .Values.ingress.appPort }}